<template>
    <main>
        <nav>
            <ul>
                <li>
                    <nuxt-link
                        to="/login">
                        login
                    </nuxt-link>
                </li>
            </ul>
        </nav>
    </main>
</template>